### ISSUE TITLE
.playFile(); TypeError

### ISSUE THREAD

**Issue by LovenDrunk** [hydrabolt/discord.js#470]
I have been having loads of problems with the .playFile(); function. The current error i'm getting is 

bot.voiceConnection.playFile(file, { volume: 0.5 });
                       
TypeError: Cannot read property 'playFile' of undefined

The function that I am writing is super simple it's just

```
 function PlayQuote(voiceChannel, file) {
    // Join the channel
    bot.joinVoiceChannel(voiceChannel);
	bot.voiceConnection.playFile(file, {volume: 0.5});
}
```
If anyone can help me I would be most grateful as I have been working on this with no success for about 2 hours now.

**Comment by GexoXYZ** [comment]
You need to be in a voiceChannel (have a voice connection) 

Use joinVoiceChannel

**Comment by Specro** [comment]
You need to use promises or callbacks for this to be sure that the second line is executed after the first one finishes it's job:
```javascript
 function PlayQuote(voiceChannel, file) {
    // Join the channel
    bot.joinVoiceChannel(voiceChannel, function(error, connection) {
      // check for errors here
      // since you get the connection from callback you don't need to get it from the bot
      connection.playFile(file, {volume: 0.5});
    });    
}
```

**Comment by LovenDrunk** [comment]
Okay so now after doing what you provided specro it seems that the bot just doesn't play anything, it doesn't even seem like it's attempting to, but it does join the channel. No errors are being thrown either.

**Comment by abalabahaha** [comment]
Hop on [the discord.js channel](https://discord.gg/0SBTUU1wZTYd2XyW)

**Comment by LovenDrunk** [comment]
I am there, I tried to ask for help last night there and I got no responses, probably because it was super late at night.

**Comment by Specro** [comment]
Check this issue #415 There's some troubleshooting info on it.

**Comment by LovenDrunk** [comment]
I feel like it's so close and it's just something small that i'm missing, I did everything that post #415 suggested. Yet I still get no audio, the bot doesn't even seem to try and play sound.

**Comment by Specro** [comment]
You checked ffmpeg and python? Try these lines in the console: 
```
python --version
ffmpeg -version
```
What OS are you using? I assume file is a string? Is the file in the root dir?

**Comment by abalabahaha** [comment]
I think this was resolved

**Comment by clb92** [comment]
How was it resolved?

**Comment by GexoXYZ** [comment]
@clb92 Check out the [troubleshooting page](http://discordjs.readthedocs.io/en/indev/troubleshooting.html)

**Comment by clb92** [comment]
@GexoXYZ I've made sure all that was as it was supposed to be, and in path environment variable too: Windows 10 (x64), Python 2.7.12, ffmpeg version N-68500-g3ba1050, re-installed Visual Studio with C++ support too and ran the npm commands.

Still doesn't work. It joins correctly, but doesn't say anything. Here's my code:

    else if (input.includes('voice')) {    //input is the message content
        bot.joinVoiceChannel('179055820053544960', function(error, connection) {
            console.log(connection);       // This correctly outputs a VoiceConnection object
            console.log(error);            // This is null
            connection.playFile("1.wav");
        });
        bot.leaveVoiceChannel('179055820053544960');
    }
