### ISSUE TITLE
ECONNRESET when streaming YouTube Audio

### ISSUE THREAD

**Issue by MikaalSky** [hydrabolt/discord.js#694]
```
{ Error: read ECONNRESET
    at exports._errnoException (util.js:1026:11)
    at TLSWrap.onread (net.js:564:26) code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' }
```
This happens seemingly randomly when playing back audio and it isn't caught by the error event.

**Comment by aister** [comment]
have u upgrade to the latest version ( 9.2.0)?

**Comment by MikaalSky** [comment]
Yeah.

**Comment by hydrabolt** [comment]
_ECONNRESET strikes yet again_ :disappointed:

**Comment by purvaldur** [comment]
+1, I'm experiencing it too. Although it's been reduced with the new 9.2.0 it still happens every now and then. I don't get the error during streams, but it happens whenever it switches to another stream.

**Comment by hydrabolt** [comment]
@purvaldur ok it must just be a stream killing issue, I'll take a look

**Comment by hydrabolt** [comment]
Probably fixed in https://github.com/hydrabolt/discord.js/commit/b0adc881f382e02dc917bef1ae103f35a7c03426, as the errors only appear when switching streams (when the prior stream ends), this should be a fairly simple fix of just listening for errors from the streams and ignoring them, seeing as though they will be destroyed fairly soon anyway.

**Comment by MikaalSky** [comment]
Will do sir! I'll update if it appears during my abuse tests.

**Comment by MikaalSky** [comment]
@hydrabolt Related but a different issue now. This existed before but this REALLY shouldn't be uncaught. 
![image](https://cloud.githubusercontent.com/assets/6946558/18492456/131a9c62-79d1-11e6-8baa-f000f951ccf7.png)

**Comment by purvaldur** [comment]
Like MikaalSky said, the econn resets still happen.

http://i.imgur.com/qWicyMJ.png

**Comment by GusCaplan** [comment]
epipe happens when you stop voice connection/dispatcher before stopping the source/stream (like you close the "pipe" before stopping the flow 😄 ). this could possibly be what you are doing, which would be affecting the results

**Comment by Trismirite** [comment]
+1 pls fix

**Comment by MikaalSky** [comment]
@GusCaplan It should still be handled.

**Comment by hydrabolt** [comment]
I don't remember closing this O>O

**Comment by Lichthagel** [comment]
+1 really want that fix

**Comment by Dewiter** [comment]
+1

**Comment by hydrabolt** [comment]
fix coming in v10

**Comment by hydrabolt** [comment]
As of https://github.com/hydrabolt/discord.js/commit/b0921ae0ef21440831a730f4d7126f1a020c64a5, ECONNRESET and other various random errors should now be fully caught and will not cause your processes to crash! 🎉

**Comment by Lichthagel** [comment]
Nice thing @hydrabolt

**Comment by ZockerBoysHD** [comment]
with d.js v13 i am getting this type of error again, any fixxes now?

**Comment by ImRodry** [comment]
> with d.js v13 i am getting this type of error again, any fixxes now?

Submit a new issue at https://github.com/discordjs/voice
